# Generated by Django 5.2 on 2026-05-29 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 29, 14, 44, 34, 496232, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 29, 14, 44, 34, 496232, tzinfo=datetime.timezone.utc)),
        ),
    ]
